title: Andrea Graglia - Frontend/Fullstack Engineer
description: I am a passionate developer with in-depth expertise in React and other frontend technologies, creating modern and high-performance user interfaces. With over 8 years of experience in the field, I have honed my skills in developing sophisticated and responsive web applications and software with different technologies.
show_downloads: false
show_pdf_downloads: true
theme: jekyll-theme-cayman
