title: Andrea Graglia
description: I am a self learned fullstack developer contractor, based in Quittengo, a beautiful and tiny village in the Italian Alps.
show_downloads: false
google_analytics:
remote_theme: andre-gra/cayman
