title: Andrea Graglia - React developer
description: I am a passionate frontend developer with in-depth expertise in React, creating modern and high-performance user interfaces. With over 5 years of experience in the field, I have honed my skills in developing sophisticated and responsive web applications.
show_downloads: false
show_pdf_downloads: true
google_analytics:
remote_theme: andre-gra/cayman
